// Purpose
// Validate implied-vol inversion before touching calibration.
//
// What should live here
// - Round-trip: price generated by BS at sigma* -> impliedVol(price) recovers sigma*.
// - Coverage for both calls and puts.
// - Failure behavior for impossible prices or bad brackets.
// - Stability checks for ATM and moderately OTM contracts.
//
// Suggested first tests
// 1. call_round_trip_recovers_input_sigma
// 2. put_round_trip_recovers_input_sigma
// 3. invalid_market_price_returns_error
// 4. solver_reports_failure_when_newton_cannot_progress
//
// This file should stay purely local and synthetic.
